spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 8899
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 10000
      maximum-pool-size: 15
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
server:
  port: 8080

mybatis:
  type-aliases-package: com.hx.oauth2.entity
  mapper-locations: mapper/*.xml
